number1 = input('enter number 1')
number2 = input('enter number 2')
number3 = input('enter number 3')
print(number1, number2)
sum = number1 + number2
print(sum)
sum = int(number1) + int(number2)
print(sum)
difference = int(number1) - int(number2)
multiplication = int(number1) * int(number2)
division = int(number1) / int(number2)
print(difference, multiplication, division)
sum = int(number1) + int(number2) + int(number3)
difference = int(number1) - int(number2) - int(number3)
division = int(number1) / int(number2) / int(number3)
import math

print(math.pow(9, 3))
print(math.gamma(9))
print(math.isfinite(9, ))
print(math.isinf(9, ))
print(math.log(9, 3))
print(math.perm(9, 3))
print(math.fabs(9))
print(nath.fmod(9, 3))
print(math.floor(9))
print(math.frexp(3))
